export const QUESTIONS = [
    {
        id: "employmentStability",
        label: "1. Employment Stability",
        description: "How long have you been in your current job or source of income?",
        type: "radio",
        options: ["<6 months", "6–12 months", "1–3 years", "3–5 years", ">5 years"],
    },
    {
        id: "monthlyIncome",
        label: "2. Monthly Income",
        description: "What is your average monthly income?",
        type: "number",
        placeholder: "e.g. 50000",
    },
    {
        id: "incomeStability",
        label: "3. Income Stability",
        description: "Is your income fixed or does it vary month to month?",
        type: "radio",
        options: ["Fixed", "Slightly variable", "Highly variable"],
    },
    {
        id: "savingsBuffer",
        label: "4. Savings & Emergency Buffer",
        description: "How many months of expenses do you currently have saved?",
        type: "radio",
        options: ["None", "<1 month", "1–3 months", "3–6 months", ">6 months"],
    },
    {
        id: "expenseRatio",
        label: "5. Monthly Expense Ratio",
        description: "How much of your income do you spend every month (approx.)?",
        type: "radio",
        options: ["<40%", "40–60%", "60–75%", ">75%"],
    },
    {
        id: "pastLoanExperience",
        label: "6. Past Loan Experience",
        description: "Have you ever taken a loan before? If yes, did you repay it on time?",
        type: "radio",
        options: [
            "Never taken",
            "Taken & repaid early/on time",
            "Taken & repaid late",
            "Taken & defaulted",
        ],
    },
    {
        id: "digitalBehavior",
        label: "7. Digital Behavior",
        description: "How often do you pay bills (phone, electricity, rent) before their due date?",
        type: "radio",
        options: ["Always early", "On time", "Sometimes late", "Usually late"],
    },
    {
        id: "dependents",
        label: "8. Dependents",
        description: "How many people depend financially on you?",
        type: "radio",
        options: ["None", "1", "2–3", "more"],
    },
    {
        id: "educationLevel",
        label: "9. Education Level",
        description: "What is your highest education completed?",
        type: "radio",
        options: ["No formal education", "High school", "UG", "PG", "Professional degree"],
    },
    {
        id: "financialDiscipline",
        label: "10. Financial Discipline",
        description: "Do you track your monthly expenses or maintain a budget?",
        type: "radio",
        options: ["Yes, strictly", "Yes, loosely", "No"],
    },
];
